apiVersion: v1
kind: Service
metadata:
  name: database-service
  labels:
    app: database
spec:
  selector:
    app: database
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

