apiVersion: apps/v1
kind: Deployment
metadata:

  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - image: 1998275/frontend:v1
          name: frontend
          ports:
          - containerPort: 3000
