apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-06-11T14:11:42Z"
  labels:
    app: backend
  name: inernalservicebackend
  namespace: default
spec:

  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: backend
  type: ClusterIP
status:
  loadBalancer: {}

